### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Pa4ok** [MCImaginarium/Thermos#1]
it can't build :(

no modifers, only git clone &  git submodule update --init --recursive

![image](https://user-images.githubusercontent.com/40999563/81486776-e634f480-925f-11ea-9753-5a353af83b78.png)

**Comment by Terminal-Access** [comment]
Ahh that's a new feature I added in to support backports for different forge versions add the following to your build arguments

-PforgeBuildNumber='{forge build}'

example usage:
./gradlew --parallel -PforgeBuildNumber='1614' clean setupCauldron installbundle

Updated the Master readme to include the new argument

Marking as closed.
